### ISSUE TITLE
Implementing other games

### ISSUE THREAD

**Issue by victorferreira** [brunooomelo/lottery#26]
Right now we can only look up the result of megasena, quina and lotofacil. I tried to implement other games but could retrieve the correct result for each game because the token is different for each game. How do I get this token? If you can provide the tokens I can implement all the remaining games Caixa offers. 

Thank you in advance.

**Comment by brunooomelo** [comment]
hey @victorferreira , in fact this api has no token, because I was used the wrong way. I need to create a webcrawler to extract the data, I looked for some lottery api but all only have paid versions.

**Comment by victorferreira** [comment]
But the current version uses a token... Is there any documentation for the API you're already using? How did you get the tokens the app is using right now?

**Comment by brunooomelo** [comment]
so this API is not public, I took the chrome network from the site, so there is no documentation so I can't provide the token.

I have no time to create a crawler

**Comment by victorferreira** [comment]
Thanks for the tip about the network console! I implemented Lotomania to test it out and it works (#27). I'll try to implement the rest of the game this weekend.
